services:
  postgres:
    image: postgres:16
    container_name: expdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Tallinn
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ../backend
    container_name: explab-backend
    restart: unless-stopped
    environment:
      DB_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
    container_name: explab-frontend
    restart: unless-stopped
    environment:
      API_URL: http://backend:8000
    ports:
      - "${FRONTEND_PORT}:8501"
    depends_on:
      backend:
        condition: service_started

volumes:
  pgdata:
